# -*- coding: utf-8 -*-
"""CHATBOT WITH RULE-BASED  RESPONSES

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mTYNc8wRAf6obKSeSq6HCbiEHQu_TBev
"""

import random

responses = {
    "hi": "Hello! How can I help you?",
    "can you play music":"Sorry I can't do that",
    "what is your name": "My name is CHATBOT AI",
    "hello": "Hi there! What can I do for you?",
    "how are you": "I'm just a bot, but thanks for asking!",
    "bye": "Goodbye! Have a nice day.",
    "thanks": "You're welcome!",
    "default": "I'm not sure I understand. Can you please be more specific?"
}

def respond(message):
    message = message.lower()
    if message in responses:
        return responses[message]
    elif "thank" in message:
        return responses["thank you"]
    elif "bye" in message:
        return responses["bye"]
    else:
        return responses["default"]

print("Welcome! Ask me anything.I can do better for u!")
while True:
    user_input = input("You: ")
    if user_input.lower() == 'bye':
        print(responses["bye"])
        break
    else:
        response = respond(user_input)
        print("CHATBOT AI:", response)